[workspace]
resolver = "2"
members = [
    "crates/ferret-core",
    "crates/ferret-shell",
    "crates/ferret-native",
    "crates/ferret-app",
    "crates/ferret-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/VertexSoftwareDev/ferret"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
